### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nikitaeverywhere** [doublefint/cos-api4node#1]
Hi @doublefint!

I want to contribute to some of your projects, including this one and mainly [vscode-cos](https://github.com/doublefint/vscode-cos). Are you okay to accept a series of pull requests which:

1. Add additional API support in this project (loading/compiling classes);
2. Improve readme of this project
3. Add support for compiling classes to [vscode-cos](https://github.com/doublefint/vscode-cos).

Please let me know! Thank you.

**Comment by doublefint** [comment]
Никита, приветствую!
Буду рад любой помощи, мне сейчас ( и ближайшие полгода ) совсем не до него, готов передать репозиторий под твое управление

**Comment by nikitaeverywhere** [comment]
Понял, спасибо!

Передавать пока, [думаю](https://hacktoberfest.digitalocean.com/), не нужно: я склонирую и отправлю несколько пулл-реквестов, хорошо? Буду рад если примешь их. Нужно будет в том числе загрузить изменения на npm парой команд.

Дам знать как справлюсь :)

**Comment by doublefint** [comment]
Хорошо, жду :)

2017-10-19 16:51 GMT+03:00 Nikita Savchenko <notifications@github.com>:

**Comment by nikitaeverywhere** [comment]
А как ты относишься к тому чтобы сделать несовместимые изменения в API `cos-api4node`? Как много проектов кроме vs-code зависят от этой библиотеки?

Например, во всех вызовах подобных к

```javascript
api.getServer((error, data) => {
    console.log(data);
});
```

Чтобы `data` был объект а не строка. Т.к. atelier API всегда возвращает JSON, гораздо удобнее положить это преобразование в сам враппер.

Это будет уже `v2.0.0`.

P.S. Если ты не против, добавишь меня в collaborators list [на npm](https://www.npmjs.com/package/cos-api4node)? Спасибо!

**Comment by doublefint** [comment]
1. Если другой возможности нет, возражать не стану. У меня только vs-code.
2. Пытался добавить (ZitRos), пишет "пользователь не найден"

2017-10-19 18:06 GMT+03:00 Nikita Savchenko <notifications@github.com>:

**Comment by nikitaeverywhere** [comment]
1. Просто это очень по конвеншнам JavaScript так сделать :)
2. На npm я [zitro](https://www.npmjs.com/~zitro).

Спасибо!

**Comment by doublefint** [comment]
1 Соглашения это важно, принимается
2 Добавил

**Comment by nikitaeverywhere** [comment]
Спасибо!

Острой необходимости в следующем нет, но перед паблишингом в npm можно ещё немного подогнать код под более "JavaScript-style". Это вопрос конечно из разряда "кому как нравится", но, например, дополнительные пробелы вокруг аргументов в экосистеме JS я почти нигде не видел.

Т.е.
```javascript
module.exports = ( conn ) => {

    const { host, port, username, password, path, version, ns } = conn
    const headers = {
        'Authorization': 'Basic ' + new Buffer( username + ':' + password ).toString( 'base64' )
    }
```
=>
```javascript
module.exports = (conn) => {

    const { host, port, username, password, path, version, ns } = conn;
    const headers = {
        Authorization: "Basic " + new Buffer(username + ":" + password).toString("base64")
    };
```

а) Убрать пробелы вокруг аргументов `f( a , b )` => `f(a, b)`
б) Добавить `;`
в) `'in${a}str'` =>`'in${ a }str'`
г) Либо все свойства сразу, либо по одному на строку в объявлении объектов
д) `spaces` => `<tab>` ([пример](https://tabs.now.sh/#/chalk/chalk/master/index.js))
е) `'` => `"` (JSON)

(обычно только последние 2 от репозитория к репозиторию варьируются)

Боюсь и не хочу показаться тем, кому "не нравится" стиль автора - я, конечно, с уважением и пониманием. Тут скорее я просто сравниваю с кодом, что за все годы опен-сорса в JS видел и делал :) Буду рад узнать твоё мнение по этому поводу.

**Comment by doublefint** [comment]
- f( a, b ) - "воздушный стиль", мне так более читабельно, быстрее взглядом "парсятся" аргументы
- ; вроде как древний холивар в js, мол, давно не нужны и только засоряют код.  У меня любимая js UI библиотека - RiotJS, нахожусь под впечатлением от нездорового минимализма ее авторов
- 'in${ a }str' // см.п. 1, не знаю даже, надо уж консистентно как-нибудь
- ' vs " - отголоски аттрибутов html, в JSON д.б. **"**, согласен.
- с одной стороны, не сторонник жестких правил, считаю, что ради выразительности, компактности, легкости восприятия можно отходить от соблюдения правил "во чтобы то ни стало". С другой, консистентность и стандарты - важно.
- space vs tabs - просто не обращаю внимания, мне все равно
думаю можно подключить какой-нибудь бьютификатор
P.S. это только мнение, но скорее всего, я не смогу уделять время проекту, так что тебе решать

**Comment by nikitaeverywhere** [comment]
Понял, оставляю оригинальный стиль :)
