### ISSUE TITLE
API Endpoints Dependence Issues

### ISSUE THREAD

**Issue by nikitaeverywhere** [doublefint/cos-api4node#3]
I am sure that this thing will need further investigation, and I will currently leave it filed here.

For \*unknown\* reasons I cannot run `getDocNames` API call right after `compile`. Example:

```js
$ node
> const api = require("./api")({
  "label": "LOCAL",
  "host": "127.0.0.1",
  "port": 57772,
  "username": "_SYSTEM",
  "password": "SYS",
  "path": "/api/atelier/",
  "version": "v1",
  "ns": "SAMPLES"
})
[Function]
> api.getDocNames({generated: 0}, (err) => console.log(err))
undefined
null // works well
> api.compile("DevProject.Robot.cls",(err)=>console.log(err))
undefined
null // works well
> api.getDocNames({generated: 0}, (err) => console.log(err))
undefined
// stucks
```

After approximately 5-10 minutes, `getDocNames` finally finishes with

```js
{ code: 503, message: 'Service Unavailable' }
```

Calling `getDocNames` before `compile`, or any other endpoints (I tested only a few) works well.

Looks like Caché problem though.

```txt
Cache for Windows (x86-64) 2017.2 (Build 543U) Fri Nov 4 2016 01:11:15 EDT
```

**Comment by doublefint** [comment]
add connection management ( see 'agent' in  http.request ) and copy cookies to request from previous response. Also add test for this case.
